// react/reduxtest/src/components/ShoppingForm.js
import React from 'react';
import {Form,Button} from 'semantic-ui-react';
import {connect} from 'react-redux';

class ShoppingForm extends React.Component {
	
	constructor(props) {
		super(props);
		this.state = {
			type:"",
			count:0,
			price:0
		}
	}
	
	onChange = (event) => {
		let state = {};
		state[event.target.name] = event.target.value;
		this.setState(state);
	}

	onSubmit = (event) => {
		event.preventDefault();
		let item = {
			type:this.state.type,
			count:this.state.count,
			price:this.state.price
		}
		let action = {
			type:"ADD_TO_LIST",
			item:item
		}
		this.props.dispatch(action);
	}
	
	render() {
		return(
			<Form onSubmit={this.onSubmit}>
				<Form.Field>
					<label htmlFor="type">Item type</label>
					<input type="text"
						   name="type"
						   onChange={this.onChange}
						   value={this.state.type}/>
				</Form.Field>
				<Form.Field>
					<label htmlFor="count">Count</label>
					<input type="number"
						   name="count"
						   onChange={this.onChange}
						   value={this.state.count}/>
				</Form.Field>
				<Form.Field>
					<label htmlFor="price">Price</label>
					<input type="number"
						   name="price"
						   onChange={this.onChange}
						   value={this.state.price}/>
				</Form.Field>
				<Button type="submit">Add</Button>
			</Form>
		)		
	}
}

export default connect()(ShoppingForm);

// vue/shoppinglistaxios/src/views/ShoppingForm.vue
<template>
	<div>
		<label for="itemtype">Item type:</label>
		<input type="text"
		       v-model="item.type"
			   name="itemtype"/>
		<br/>
		<label for="price">Price:</label>
		<input type="number"
			   minimum="0"
			   step="0.01"
			   name="price"
			   v-model="item.price"/>
		<br/>
		<label for="count">Count:</label>
		<input type="number"
			   minimum="0"
			   name="count"
			   v-model="item.count"/>
		<br/>
		<button v-on:click="addToList()">Add</button>
	</div>
</template>
<script>
export default {
	name:"ShoppingForm",
	data() {
		return {
			item: {
				id:0,
				type:"",
				price:0,
				count:0
			}
		}
	},
	methods: {
		addToList: function() {
			this.$store.dispatch("addToList",this.item);
			this.item = {
				id:0,
				type:"",
				price:0,
				count:0
			}
		}
	}
}
</script>
