// angular/simpleeanexample/src/app/components/shoppingform.component.ts
import {Component} from '@angular/core';
import {ShoppingService} from '../services/shoppingservice.service';
import {ShoppingItem} from '../models/shoppingitem.model';

@Component({
	selector:'shoppingform',
	templateUrl:'./shoppingform.component.html'
})
export class ShoppingForm {	
	public shoppingitem:ShoppingItem = new ShoppingItem("",0,0,0);
	
	constructor(private _shoppingService:ShoppingService) {}

	addToList() {
		this._shoppingService.addToList(this.shoppingitem);
		this.shoppingitem = new ShoppingItem("",0,0,0);
	}

}
<form (ngSubmit)="addToList()" #shoppingForm="ngForm">
	<div class="form-group">
	<label for="type">Item type:</label>
	<input type="text" name="type" id="type"
	 [(ngModel)]="shoppingitem.type" />
	</div>
	<div class="form-group">
	<label for="price">Price:</label>
	<input type="number" step="0.01" minimum="0"
	 name="price" id="price" [(ngModel)]="shoppingitem.price"/>
	</div>
	<div class="form-group">
	 <label for="count">Count:</label>
	<input type="number" step="1" minimum="0"
	 name="count" id="count" [(ngModel)]="shoppingitem.count"/>
	</div>
	<button class="btn btn-secondary" type="submit">Add</button>
</form>

// vue/shoppinglistaxios/src/views/ShoppingForm.vue
<template>
	<div>
		<label for="itemtype">Item type:</label>
		<input type="text"
		       v-model="item.type"
			   name="itemtype"/>
		<br/>
		<label for="price">Price:</label>
		<input type="number"
			   minimum="0"
			   step="0.01"
			   name="price"
			   v-model="item.price"/>
		<br/>
		<label for="count">Count:</label>
		<input type="number"
			   minimum="0"
			   name="count"
			   v-model="item.count"/>
		<br/>
		<button v-on:click="addToList()">Add</button>
	</div>
</template>
<script>
export default {
	name:"ShoppingForm",
	data() {
		return {
			item: {
				id:0,
				type:"",
				price:0,
				count:0
			}
		}
	},
	methods: {
		addToList: function() {
			this.$store.dispatch("addToList",this.item);
			this.item = {
				id:0,
				type:"",
				price:0,
				count:0
			}
		}
	}
}
</script>
