// angular/shoppingexercise-part1/src/app/components/shoppinglist.component.ts
import {Component} from '@angular/core';
import {ShoppingItem} from '../models/shoppingitem.model';

@Component({
	selector:'shoppinglist',
	templateUrl:'./shoppinglist.component.html',
	styleUrls:['./shoppinglist.component.css']
})
export class ShoppingList {
	private id:number = 100;
	public shoppingitem:ShoppingItem = new ShoppingItem("",0,0,0);
	public shoppinglist:ShoppingItem[] = []
	public mode:string = "Add";
	
	addToList() {
		if(this.shoppingitem.id === 0) {
			this.shoppingitem.id = this.id;
			this.id++;
			this.shoppinglist.push(this.shoppingitem);
		} else {
			for(let i=0;i<this.shoppinglist.length;i++) {
				if(this.shoppinglist[i].id === this.shoppingitem.id) {
					this.shoppinglist.splice(i,1,this.shoppingitem);
				}
			}
			this.mode = "Add";
		}
		this.shoppingitem = new ShoppingItem("",0,0,0);
	}
	
	removeFromList(idx) {
		this.shoppinglist.splice(idx,1);
	}
	
	editItem(idx) {
		this.mode === "Edit";
		this.shoppingitem = this.shoppinglist[idx];
	}
}
<div>
<h1>The ShoppingList</h1>
<form (ngSubmit)="addToList()" #shoppingForm="ngForm">
	<label for="type">Item type:</label>
	<input type="text" name="type" id="type"
	 [(ngModel)]="shoppingitem.type" />
	 <br/>
	<label for="price">Price:</label>
	<input type="number" step="0.01" minimum="0"
	 name="price" id="price" [(ngModel)]="shoppingitem.price"/>
	 <br/>
	 <label for="count">Count:</label>
	<input type="number" step="1" minimum="0"
	 name="count" id="count" [(ngModel)]="shoppingitem.count"/>
	<br/>
	<input type="submit" value="Add"/>
</form>
<table class="centertable">
	<thead>
		<tr>
			<th>Type</th>
			<th>Price</th>
			<th>Count</th>
			<th>Remove</th>
			<th>Edit</th>
		</tr>
	</thead>
	<tbody>
		<tr *ngFor="let item of shoppinglist;let idx=index">
			<td>{{item.type}}</td>
			<td>{{item.price}}</td>
			<td>{{item.count}}</td>
			<td><button (click)="removeFromList(idx)">Buy</button></td>
			<td><button (click)="editItem(idx)">Edit</button></td>
		</tr>
	</tbody>
</table>
</div>

// vue/shoppinglistvuex/src/views/ShoppingList.vue
<template>
	<table>
		<thead>
			<tr>
				<th>Type</th>
				<th>Price</th>
				<th>Count</th>
				<th>Buy</th>
				<th>Edit</th>
			</tr>
		</thead>
		<tbody>
			<tr v-for="item in this.$store.state.list" :key="item.id">
				<template v-if="editId !== item.id">
					<td>{{item.type}}</td>
					<td>{{item.price}}</td>
					<td>{{item.count}}</td>
					<td><button v-on:click="remove(item.id)">Buy</button></td>
					<td><button v-on:click="edit(item.id)">Edit</button></td>
				</template>
				<template v-else>
					<td><input type="text"
							   v-model="type"/></td>
					<td><input type="number"
								v-model="price"/></td>
					<td><input type="count"
								v-model="count"/></td>
					<td><button v-on:click="saveItem()">Save</button></td>
					<td><button v-on:click="cancel()">Cancel</button></td>
				</template>
			</tr>
		</tbody>		
	</table>
</template>
<script>
export default {
	name:"ShoppingList",
	props:['list'],
	data() {
		return {
			editId:-1,
			type:"",
			price:0,
			count:0
		}
	},
	methods: {
		remove:function(id) {
			this.$store.dispatch("removeFromList",id);
		},
		edit:function(id) {
			this.editId = id;
			for(let i=0;i<this.$store.state.list.length;i++) {
				if(id === this.$store.state.list[i].id) {
					this.type = this.$store.state.list[i].type;
					this.price = this.$store.state.list[i].price;
					this.count = this.$store.state.list[i].count;
				}
			}
		},
		cancel:function() {
			this.editId = -1;
		},
		saveItem:function() {
			let tempItem = {
				id:this.editId,
				type:this.type,
				price:this.price,
				count:this.count
			}
			this.$store.dispatch("editItem",tempItem);
			this.editId = -1;
			this.type = "";
			this.count = 0;
			this.price = 0;
		}
	}	
}
</script>
