// vue/shoppinglist/src/components/ShoppingForm.vue
<template>
	<div>
		<label for="itemtype">Item type:</label>
		<input type="text"
		       v-model="item.type"
			   name="itemtype"/>
		<br/>
		<label for="price">Price:</label>
		<input type="number"
			   minimum="0"
			   step="0.01"
			   name="price"
			   v-model="item.price"/>
		<br/>
		<label for="count">Count:</label>
		<input type="number"
			   minimum="0"
			   name="count"
			   v-model="item.count"/>
		<br/>
		<button v-on:click="addToList()">Add</button>
	</div>
</template>
<script>
export default {
	name:"ShoppingForm",
	data() {
		return {
			item: {
				id:0,
				type:"",
				price:0,
				count:0
			}
		}
	},
	methods: {
		addToList: function() {
			this.$emit("add-to-list",this.item);
			this.item = {
				id:0,
				type:"",
				price:0,
				count:0
			}
		}
	}
}
</script>

// react/hooks-example3/src/components/ShoppingForm.js
import React, {useState} from 'react';
import {Form,Button} from 'semantic-ui-react';

const ShoppingForm = ({addToList}) => {
	
	const [form,setValues] = useState({
		type:"",
		count:0,
		price:0	
	})
	
	const onChange = (event) => {
		setValues({
			...form,
			[event.target.name]:event.target.value
		})	
	}
	
	const onSubmit = (event) => {
		event.preventDefault();
		addToList(form);
	}
	
	return (
		<Form onSubmit={onSubmit}>
			<Form.Field>
				<label htmlFor="type">Item Type</label>
				<input type="text"
					   name="type"
					   onChange={onChange}
					   value={form.type}/>
			</Form.Field>
			<Form.Field>
				<label htmlFor="count">Count</label>
				<input type="number"
					   name="count"
					   onChange={onChange}
					   value={form.count}/>
			</Form.Field>
			<Form.Field>
				<label htmlFor="price">Price</label>
				<input type="number"
					   name="price"
					   onChange={onChange}
					   value={form.price}/>
			</Form.Field>
			<Button type="submit">Add</Button>
		</Form>
	)
}

export default ShoppingForm;
